# -*- coding: utf-8 -*-
"""num_sounds.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZDGBWV9zlswyCiKOP1foSxjy3yw8D0rM
"""

!pip install gTTS googletrans==4.0.0-rc1

digit_to_thai_word = {
    '0': 'ศูนย์',
    '1': 'หนึ่ง',
    '2': 'สอง',
    '3': 'สาม',
    '4': 'สี่',
    '5': 'ห้า',
    '6': 'หก',
    '7': 'เจ็ด',
    '8': 'แปด',
    '9': 'เก้า'
}

from gtts import gTTS
from googletrans import Translator

# Define the directory where you want to save the .mp3 files
output_directory = '/content/num/'

# Iterate through the dictionary and create .mp3 files
for n in digit_to_thai_word:
    tts = gTTS(text=n, lang='th')
    tts.save(f'{output_directory}{n}.mp3')

print("Sound files downloaded successfully.")

!zip -r nums.zip /content/num